import { NextRequest, NextResponse } from 'next/server'

const AUTH_COOKIE_NAME = 'mom_auth'
const GUEST_USAGE_COOKIE_NAME = 'mom_guest_usage'
const GUEST_FREE_LIMIT = 5

const GUEST_USAGE_COOKIE_OPTIONS = {
  httpOnly: true,
  sameSite: 'lax' as const,
  secure: process.env.NODE_ENV === 'production',
  path: '/',
  maxAge: 60 * 60 * 24 * 180,
}

const SYSTEM_PROMPT = `You are an expert corporate secretary and professional meeting facilitator. 
Your task is to convert raw meeting transcripts into polished, professional Minutes of Meeting (MoM) documents.

Follow this exact structure:

# Minutes of Meeting

**Date:** [Today's date]  
**Generated by:** AI Meeting Assistant  
**Participants:** [@participant1, @participant2, ...]  

---

## Executive Summary
A concise 2–3 sentence overview of what was discussed and decided.

---

## Key Discussion Points
Bullet points covering all major topics raised during the meeting. Be structured and clear.

---

## Decisions Made
List every concrete decision or resolution reached. Use a numbered list.

---

## Action Items
| Action | Owner | Priority |
|--------|-------|----------|
| [task] | [@person if mentioned, else "@team"] | [High/Medium/Low] |

---

## Next Steps
Brief description of follow-up activities and any mentioned deadlines.

---

*These minutes were auto-generated by AI Meeting Assistant. Please review for accuracy before distributing.*

Rules:
- Be faithful to what was said — do not invent information
- Use formal, professional language
- If the transcript is unclear or too short, note that explicitly
- Extract all people who spoke or were assigned work and list them in **Participants** at the top
- Wherever a person name appears, convert it to a lowercase @handle (examples: Aniket -> @aniket, Isha -> @isha)
- Keep @handles consistent across all sections, including Executive Summary, Decisions, and Next Steps
- In **Action Items**, always set Owner as an @handle; if no owner is mentioned, use @team
- Dates should use the format: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
`

type OpenRouterResponse = {
  choices?: Array<{
    message?: {
      content?: string | Array<{ type?: string; text?: string }>
    }
  }>
  error?: {
    message?: string
  }
}

const OPENROUTER_URL = 'https://openrouter.ai/api/v1/chat/completions'

const PREMIUM_MODEL_FALLBACKS = [
  'openai/gpt-5.4-mini',
  'anthropic/claude-sonnet-4.6',
  'google/gemini-2.5-flash',
]

type CreditsState = {
  isLoggedIn: boolean
  usage: number
  creditsRemaining: number | null
}

function parseNonNegativeInt(value: string | undefined): number {
  const parsed = Number.parseInt(value ?? '0', 10)
  if (Number.isNaN(parsed) || parsed < 0) {
    return 0
  }
  return parsed
}

function readCreditsState(req: NextRequest): CreditsState {
  const isLoggedIn = req.cookies.get(AUTH_COOKIE_NAME)?.value === '1'

  if (isLoggedIn) {
    return {
      isLoggedIn: true,
      usage: 0,
      creditsRemaining: null,
    }
  }

  const usage = parseNonNegativeInt(req.cookies.get(GUEST_USAGE_COOKIE_NAME)?.value)
  return {
    isLoggedIn: false,
    usage,
    creditsRemaining: Math.max(0, GUEST_FREE_LIMIT - usage),
  }
}

function extractResponseText(data: OpenRouterResponse): string {
  const content = data?.choices?.[0]?.message?.content

  if (typeof content === 'string') {
    return content.trim()
  }

  if (Array.isArray(content)) {
    return content
      .map((part) => (typeof part?.text === 'string' ? part.text : ''))
      .join('')
      .trim()
  }

  return ''
}

export async function GET(req: NextRequest) {
  const creditsState = readCreditsState(req)

  return NextResponse.json({
    isLoggedIn: creditsState.isLoggedIn,
    creditsRemaining: creditsState.creditsRemaining,
    freeLimit: GUEST_FREE_LIMIT,
  })
}

export async function POST(req: NextRequest) {
  const creditsState = readCreditsState(req)

  if (!creditsState.isLoggedIn && creditsState.creditsRemaining === 0) {
    return NextResponse.json(
      {
        error: 'Free credits exhausted. Please log in to continue generating MoM.',
        isLoggedIn: false,
        creditsRemaining: 0,
        freeLimit: GUEST_FREE_LIMIT,
      },
      { status: 403 }
    )
  }

  let transcript = ''
  try {
    const payload = await req.json()
    transcript = typeof payload?.transcript === 'string' ? payload.transcript : ''
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  if (!transcript.trim()) {
    return NextResponse.json({ error: 'No transcript provided' }, { status: 400 })
  }

  const apiKey = process.env.OPENROUTER_API_KEY
  if (!apiKey) {
    return NextResponse.json({ error: 'OpenRouter API key not configured' }, { status: 500 })
  }

  let lastErr = 'Unknown error'
  let lastStatus = 502
  let lastModel = 'none'

  for (const model of PREMIUM_MODEL_FALLBACKS) {
    try {
      const response = await fetch(OPENROUTER_URL, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000',
          'X-Title': 'AI Meeting Minutes',
        },
        body: JSON.stringify({
          model,
          messages: [
            {
              role: 'system',
              content: SYSTEM_PROMPT,
            },
            {
              role: 'user',
              content: `Please generate professional Minutes of Meeting from the following transcript:\n\n${transcript}`,
            },
          ],
          temperature: 0.3,
          top_p: 0.95,
          max_tokens: 4096,
        }),
        signal: req.signal,
      })

      const raw = await response.text()

      if (!response.ok) {
        lastErr = raw || 'Unknown upstream error'
        lastStatus = response.status
        lastModel = model
        console.warn(`[generate-mom] Model ${model} failed (${response.status}): ${lastErr}`)
        continue
      }

      let data: OpenRouterResponse
      try {
        data = JSON.parse(raw) as OpenRouterResponse
      } catch {
        lastStatus = 502
        lastModel = model
        lastErr = 'OpenRouter returned non-JSON response'
        console.warn(`[generate-mom] Model ${model} returned non-JSON payload`)
        continue
      }

      const text = extractResponseText(data)

      if (!text) {
        lastStatus = 502
        lastModel = model
        lastErr = JSON.stringify(data?.error ?? { error: 'Empty model response' })
        console.warn(`[generate-mom] Model ${model} returned empty text`, data?.error)
        continue
      }

      if (creditsState.isLoggedIn) {
        return NextResponse.json({
          mom: text,
          model,
          isLoggedIn: true,
          creditsRemaining: null,
          freeLimit: GUEST_FREE_LIMIT,
        })
      }

      const nextUsage = creditsState.usage + 1
      const nextCreditsRemaining = Math.max(0, GUEST_FREE_LIMIT - nextUsage)

      const successResponse = NextResponse.json({
        mom: text,
        model,
        isLoggedIn: false,
        creditsRemaining: nextCreditsRemaining,
        freeLimit: GUEST_FREE_LIMIT,
      })

      successResponse.cookies.set(GUEST_USAGE_COOKIE_NAME, String(nextUsage), GUEST_USAGE_COOKIE_OPTIONS)

      return successResponse
    } catch (err: unknown) {
      if (err instanceof Error && err.name === 'AbortError') {
        return NextResponse.json({ error: 'Request aborted' }, { status: 499 })
      }
      console.warn(`[generate-mom] Error with model ${model}:`, err)
      lastStatus = 502
      lastModel = model
      lastErr = String(err)
    }
  }

  console.error(`[generate-mom] All OpenRouter models failed. Last model: ${lastModel}. Last error: ${lastErr}`)
  return NextResponse.json(
    { error: `OpenRouter request failed on all models. Last model: ${lastModel}. Last error: ${lastErr}` },
    { status: lastStatus }
  )
}
